export const expenseCategories = [
	{ category: 'Other', icon: 'other' },
	{ category: 'Advertising', icon: 'advertising' },
	{ category: 'Airlines', icon: 'airlines' },
	{ category: 'Alcohol and Bars', icon: 'alcohol-and-bars' },
	{ category: 'Books and Newspaper', icon: 'books-and-newspaper' },
	{ category: 'Car Rental', icon: 'car-rental' },
	{ category: 'Charity', icon: 'charity' },
	{ category: 'Clothing', icon: 'clothing' },
	{ category: 'Conferences', icon: 'conferences' },
	{ category: 'Education', icon: 'education' },
	{ category: 'Entertainment', icon: 'entertainment' },
	{ category: 'Facilities Expense', icon: 'facilities-expense' },
	{
		category: 'Financial Institution and Fees',
		icon: 'financial-institution-and-fees',
	},
	{ category: 'Fuel and Gas', icon: 'fuel-and-gas' },
	{ category: 'Government Service', icon: 'government-service' },
	{ category: 'Grocery', icon: 'grocery' },
	{ category: 'Food Delivery', icon: 'food-delivery' },
	{ category: 'Transportation', icon: 'transportation' },
	{ category: 'Insurance', icon: 'insurance' },
	{ category: 'Medical', icon: 'medical' },
	{ category: 'Internet', icon: 'internet' },
	{ category: 'Parking', icon: 'parking' },
	{ category: 'Office Supplies', icon: 'office-supplies' },
	{ category: 'Restaurant', icon: 'restaurant' },
	{ category: 'Software', icon: 'software' },
	{ category: 'Taxes', icon: 'taxes' },
	{ category: 'Utilities', icon: 'utilities' },
	{ category: 'Vehicle Expenses', icon: 'vehicle-expenses' },
] as const;
