export const expenseCategories = [
	{ label: 'Other', icon: 'other' },
	{ label: 'Advertising', icon: 'advertising' },
	{ label: 'Airlines', icon: 'airlines' },
	{ label: 'Alcohol & Bars', icon: 'alcohol-and-bars' },
	{ label: 'Books & Newspaper', icon: 'books-and-newspaper' },
	{ label: 'Car Rental', icon: 'car-rental' },
	{ label: 'Charity', icon: 'charity' },
	{ label: 'Clothing', icon: 'clothing' },
	{ label: 'Conferences', icon: 'conferences' },
	{ label: 'Education', icon: 'education' },
	{ label: 'Entertainment', icon: 'entertainment' },
	{ label: 'Facilities Expense', icon: 'facilities-expense' },
	{
		label: 'Financial Institution & Fees',
		icon: 'financial-institution-and-fees',
	},
	{ label: 'Fuel & Gas', icon: 'fuel-and-gas' },
	{ label: 'Government Service', icon: 'government-service' },
	{ label: 'Grocery', icon: 'grocery' },
	{ label: 'Food Delivery', icon: 'food-delivery' },
	{ label: 'Transportation', icon: 'transportation' },
	{ label: 'Insurance', icon: 'insurance' },
	{ label: 'Medical', icon: 'medical' },
	{ label: 'Internet', icon: 'internet' },
	{ label: 'Parking', icon: 'parking' },
	{ label: 'Office Supplies', icon: 'office-supplies' },
	{ label: 'Restaurant', icon: 'restaurant' },
	{ label: 'Software', icon: 'software' },
	{ label: 'Taxes', icon: 'taxes' },
	{ label: 'Utilities', icon: 'utilities' },
	{ label: 'Vehicle Expenses', icon: 'vehicle-expenses' },
] as const;
