export const incomeCategories = [
	{ icon: 'other', label: 'Other' },
	{ icon: 'salary', label: 'Salary' },
	{ icon: 'freelance', label: 'Freelance' },
	{ icon: 'business-income', label: 'Business Income' },
	{ icon: 'bonuses-and-commission', label: 'Bonuses & Commissions' },
	{ icon: 'overtime-pay', label: 'Overtime Pay' },
	{ icon: 'dividens', label: 'Dividens' },
	{ icon: 'interest-income', label: 'Interest Income' },
	{ icon: 'capital-gains', label: 'Capital Gains' },
	{ icon: 'rental-income', label: 'Rental Income' },
	{ icon: 'royalties', label: 'Royalties' },
	{ icon: 'affiliate-marketing', label: 'Affiliate Marketing' },
	{ icon: 'advertising', label: 'Advertising' },
	{ icon: 'dropshipping', label: 'Dropshipping' },
	{ icon: 'pension', label: 'Pension' },
	{ icon: 'unemployment-benefits', label: 'Unemployment Benefits' },
	{ icon: 'child-support', label: 'Child Support' },
	{ icon: 'alimony', label: 'Alimony' },
	{ icon: 'gifts-and-donations', label: 'Gifts & Donations' },
	{ icon: 'lottery-and-gambling', label: 'Lottery & Gambling' },
	{ icon: 'side-hustles', label: 'Side Hustles' },
];
